CREATE TABLE medications (
    START             DATETIME,
    STOP              DATETIME,
    PATIENT           VARCHAR(36),
    PAYER             VARCHAR(36),
    ENCOUNTER         VARCHAR(36),
    CODE              VARCHAR(50),
    DESCRIPTION       VARCHAR(500),
    BASE_COST         DECIMAL(10,2),
    PAYER_COVERAGE    DECIMAL(10,2),
    DISPENSES         INT,
    TOTALCOST         DECIMAL(10,2),
    REASONCODE        VARCHAR(50),
    REASONDESCRIPTION VARCHAR(500),
    FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    FOREIGN KEY (PAYER) REFERENCES payers(Id),
    FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)

);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/medications.csv'
INTO TABLE medications
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(@START, @STOP, PATIENT, PAYER, ENCOUNTER, CODE, DESCRIPTION,
 @BASE_COST, @PAYER_COVERAGE, @DISPENSES, @TOTALCOST, REASONCODE, REASONDESCRIPTION)
SET
    START           = STR_TO_DATE(NULLIF(@START, ''), '%Y-%m-%dT%H:%i:%sZ'),
    STOP            = STR_TO_DATE(NULLIF(@STOP, ''), '%Y-%m-%dT%H:%i:%sZ'),
    BASE_COST       = NULLIF(@BASE_COST, ''),
    PAYER_COVERAGE  = NULLIF(@PAYER_COVERAGE, ''),
    DISPENSES       = NULLIF(@DISPENSES, ''),
    TOTALCOST       = NULLIF(@TOTALCOST, '');
    

